//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace monitorscreenshot.Properties {
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "5.1.0.5216")]
	internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
		
		private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
		
		public static Settings1 Default {
			get {
				return defaultInstance;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Vui lòng nhập mật khẩu")]
		public string INPUT_PASSWORD {
			get {
				return ((string)(this["INPUT_PASSWORD"]));
			}
			set {
				this["INPUT_PASSWORD"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("vui lòng nhập username")]
		public string INPUT_USERNAME {
			get {
				return ((string)(this["INPUT_USERNAME"]));
			}
			set {
				this["INPUT_USERNAME"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string pass {
			get {
				return ((string)(this["pass"]));
			}
			set {
				this["pass"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string user {
			get {
				return ((string)(this["user"]));
			}
			set {
				this["user"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Thông tin đăng nhập chưa đúng, vui lòng kiểm tra lại username hoặc mật khẩu")]
		public string USERNAME_OR_PASSWORD_INCORECT {
			get {
				return ((string)(this["USERNAME_OR_PASSWORD_INCORECT"]));
			}
			set {
				this["USERNAME_OR_PASSWORD_INCORECT"] = value;
			}
		}
	}
}
